In [2]:
import numpy as np

arr1=np.array([1,2,3,4])
print(arr1)

[1 2 3 4]


In [3]:
print(type(arr1))

<class 'numpy.ndarray'>


In [4]:
print(arr1.shape)

(4,)


In [5]:
arr2=np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [7]:
print(arr2.shape)

(2, 4)


In [10]:
arr3=np.array([1,2,3,4])
print(arr3.shape)
arr3=arr3.reshape(1,4)
print(arr3)
print(arr3.shape)

(4,)
[[1 2 3 4]]
(1, 4)
