In [4]:
import numpy as np

arr1= np.array([1,2,3,4])
print(arr1)

[1 2 3 4]


In [16]:
print(arr1.shape)
print(arr1.reshape(4,1))
print(np.arange(0,10,2))
print(np.ones((3,3)))
print(np.eye(3))
print(arr1.dtype)

(4,)
[[1]
 [2]
 [3]
 [4]]
[0 2 4 6 8]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
int64


# Vectorised Operations

In [21]:
arr1=np.array([1,2,3,4])
arr2=np.array([10,20,30,40])
print(arr1+arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)


[11 22 33 44]
[ -9 -18 -27 -36]
[ 10  40  90 160]
[0.1 0.1 0.1 0.1]


In [25]:
print(np.sqrt(arr2))
print(np.exp(arr1))
print(np.log(arr1))

[3.16227766 4.47213595 5.47722558 6.32455532]
[ 2.71828183  7.3890561  20.08553692 54.59815003]
[0.         0.69314718 1.09861229 1.38629436]


In [32]:
arr2=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2)
print(arr2[0,0])
print(arr2[0:,1:])
print(arr2[0:2,0:2])




[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
[[2 3]
 [5 6]
 [8 9]]
[[1 2]
 [4 5]]
2.5


In [36]:
print(arr1.mean())
print(arr1.std())
print(arr1.var())

arr1[arr1>2]

2.5
1.118033988749895
1.25


array([3, 4])